### DISCUSSION TITLE
When running on docker: Attempted to load @next/swc-linux-arm64-gnu, but it was not installed

### DISCUSSION THREAD

**Discussion by NasserBvB** [keystonejs/keystone#7693] [Questions] [answered]
I'm trying to run dockerize a keystone application .
So I started by creating a starter keystone application . 
I added a Dockerfile with the following :
```
FROM node:16
WORKDIR /usr/app
COPY . .
RUN yarn dev
```
I also added a docker-compose.yml file with the following :
```
version: '3.3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - app:.:/usr/app
volumes:
  app:

```
After running `docker-compose up -d` I got the following error that indicates that there was a problem with nextjs  swc inside keystone core.
Here is a screenshot of the error I'm getting .
<img width="1029" alt="Screen Shot 2022-06-24 at 20 16 37" src="https://user-images.githubusercontent.com/48838783/175651550-6e5f673d-f8dc-44e7-8bcd-70fae643d884.png">

I'm using mac m1.
node version: 16
npm version : 8
