### DISCUSSION TITLE
Is it possible to customize the relationship cards rendering?

### DISCUSSION THREAD

**Discussion by victorafael-com** [keystonejs/keystone#7896] [Questions]
I'm starting to use keystone and so far I'm really enjoying the experience.

But looks like it is not possible to change the way some components render. I know this is complex to integrate but I think there are some few adjustments that could make the project even more customizable, example, having exposed class names for major components and allowing us to inject custom css on the admin UI, bellow is what I want to achieve:

Relationship Cards:
![image](https://user-images.githubusercontent.com/11251477/188805017-6df98f88-acea-4ba5-a23c-a5d5f61b1929.png)

Now I went to the root element of the relationship cards and added the css class: "cards-root". and injected this custom css via inspector:
```css
.cards-root li>div>div{
    display: flex;
    flex-direction: row;
    align-items: baseline;
}
.cards-root li>div>div>div{
    margin-top: 0;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    flex: 1;
}
.cards-root li label{
    font-size: 0.75em;
}
```
Result:
![image](https://user-images.githubusercontent.com/11251477/188805294-5c81c4df-c307-49b4-a448-870487dc2d87.png)
