### ISSUE TITLE
0.4:  Cannot resize code field textarea

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2012]
It appears to have `resize: vertical;` but for some reason is not taking effect.

**Comment by theshaune** [comment]
You also need to have `overflow` set, and you will need to target the correct divs, this may be awkward due to the nested structure, you may also need to adjust the `height`.

```css
{
  resize: both;
  overflow: auto;
}
```

Hope this helps!
