### ISSUE TITLE
Can't deploy by docker/docker-compose

### ISSUE THREAD

**Issue by williamhqs** [keystonejs/keystone#2104]
# Bug report

I am trying to deploy keystoneJS app on the server. Before that I want to test it locally.

I started mongoDB locally. Then use the Dockerfile from the documentation https://www.keystonejs.com/guides/deployment here, I can't run it. I get the error below:

```
✖ Connecting to database
Error: Server selection timed out after 30000 ms
    at /home/node/node_modules/@keystonejs/utils/dist/utils.cjs.prod.js:54:26
    at async executeDefaultServer (/home/node/node_modules/@keystonejs/keystone/bin/utils.js:109:3) {
  errors: {
    MongooseAdapter: MongoTimeoutError: Server selection timed out after 30000 ms
        at Timeout._onTimeout (/home/node/node_modules/mongodb/lib/core/sdam/server_selection.js:308:9)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      name: 'MongoTimeoutError',
      reason: [MongoNetworkError],
      [Symbol(mongoErrorContextSymbol)]: {}
    }
  }
}
error Command failed with exit code 1.
```

So I think could be docker didn't know about local `mongodb://localhost:27017`. 

Then I decided to use docker-compose:

Here is the **docker-compose.yml**
```

version: '3'
services:
  app:
    container_name: my-admin
    restart: always
    build: .
    volumes:
        - .:/mycode
    environment:
        - MONGO_URI=mongodb://mongo:27017
    ports:
    - "80:3030"
    links:
        - mongo
  mongo:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"

```
Same error.

## To Reproduce

Also tried this:

```
const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new Adapter({mongoUri: "mongodb://mongo:27017/myapp"}),
  onConnect: initialiseData,
});
```

`run docker build .` then get this timeout error.

## System information

- OS: macOS

Could anyone tell my am on the right way? Thanks!
