### ISSUE TITLE
Example of Docker-Compose with Hot Reload

### ISSUE THREAD

**Issue by wcalebgray** [keystonejs/keystone#2805]
Hello all,

I recently started a new project with KeystoneJS and wanted to develop it using Docker-Compose with a nodemon-like hot reload of the server upon any change. Unfortunately, I couldn't find any examples of what to use for the newest version of KeystoneJS. So, I cobbled a few things together and got it working. I wanted to log this here in case someone else finds it useful. If it's really useful, let me know and I'll submit a PR to add to the docs. Please note, my setup was using Postgres and not MongoDB, but that shouldn't be hard to change:

docker-compose.yaml
```
version: '3'
services:
  devbox:
    container_name: dev-service-name
    build:
      context: .
      dockerfile: devbox.dockerfile
    volumes:
        - .:/home/node/app
        - node_modules:/home/node/app/node_modules
    environment:
        - DATABASE_URL=postgres://user:password@postgres:5432/database-name
    ports:
    - "3000:3000"
    command: ["yarn", "dev"]
    links:
        - postgres
  production-server:
    container_name: service-name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/app
    environment:
        - DATABASE_URL=postgres://user:password@postgres:5432/database-name
    ports:
    - "3000:3000"
    command: ["./dumb-init", "yarn", "start"]
    links:
        - postgres
  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=database-name
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
  node_modules:
```

devbox.dockerfile (for local development)
```
# https://docs.docker.com/samples/library/node/
ARG NODE_VERSION=12.10.0

FROM node:${NODE_VERSION}-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN yarn install

COPY --chown=node:node . .

EXPOSE 3000
CMD ["yarn", "dev"]
```

Dockerfile (for building and running in production; this is straight copy/paste from the docs already existing):
```
# https://docs.docker.com/samples/library/node/
ARG NODE_VERSION=12.10.0
# https://github.com/Yelp/dumb-init/releases
ARG DUMB_INIT_VERSION=1.2.2

# Build container
FROM node:${NODE_VERSION}-alpine AS build
ARG DUMB_INIT_VERSION

WORKDIR /home/node

RUN apk add --no-cache build-base python2 yarn && \
  wget -O dumb-init -q https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_amd64 && \
  chmod +x dumb-init
ADD . /home/node
RUN yarn install && yarn build && yarn cache clean

# Runtime container
FROM node:${NODE_VERSION}-alpine

WORKDIR /home/node

COPY --from=build /home/node /home/node

EXPOSE 3000
CMD ["./dumb-init", "yarn", "start"]
```

Hope it helps someone!
