### ISSUE TITLE
Docker issue with production build images and files

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#6137]
# Bug report

## Describe the bug

This is what I found, it creates symlinks with absolute path which breaks inside the container. I do not usually build the container. I usually use prebuilt nodejs container and run it with the mapped app path. 

When running in docker after building it, it complained 
```sh
errno: -2,
core_1  |   syscall: 'stat',
core_1  |   code: 'ENOENT',
core_1  |   path: '/home/node/app/.keystone/admin/public/files'
```

## To Reproduce

run `yarn build` and then use following docker compose to run the container
```yaml
version: "2"
services:
  core:
    image: "node:lts"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3100"
    command: "yarn start"
```

## Expected behaviour

There should not be and error and it should run without the issue.

## System information

ubuntu with docker

## Additional context

I can fix it by manually creating symlinks with relative path in `.keystone/admin/public/` for files and images.
