### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by satyajitghana** [keystonejs/keystone#6150]
# Bug report

## Describe the bug

There's a node related error when `yarn dev` is started, seems to be related to database connection

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. `yarn create keystone-5-app`
2. Choose Prisma Postgres
3. cd my-app
4. `DATABASE_URL=postgres://postgres:postgres@postgres_db/ yarn dev`

Use this Dockerfile

```Dockerfile
from node:stretch
```

Use this `docker-compose.yml`

```yml
version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        ports:
            - "3000:3000"
        depends_on:
            - postgres_db

    postgres_db:
        image: postgres:latest
        restart: always
        env_file:
            - database.env
        volumes:
            - myapp-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    myapp-db:
```

## Expected behaviour

The Admin UI should show up on port `3000`

## Logs

```
root@2a3f2d026a71:/workspace/my-app# yarn dev
yarn dev
yarn run v1.22.5
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev
ℹ Command: keystone dev
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
No cookieSecret value was provided. Please generate a secure value and add it to your app. Until this is done, a random cookieSecret will be generated each time Keystone is started. This will cause sessions to be reset between restarts. See [https://www.keystonejs.com/keystonejs/keystone/#cookiesecret] for details.
✔ Initialised Keystone instance
⠋ Connecting to database(node:5555) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
⠧ Connecting to database/usr/local/bin/node[5555]: ../src/node_http_parser.cc:567:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
 1: 0xb22900 node::Abort() [/usr/local/bin/node]
 2: 0xb2297e  [/usr/local/bin/node]
 3: 0xb39fe2  [/usr/local/bin/node]
 4: 0xd72a0b  [/usr/local/bin/node]
 5: 0xd73ebc  [/usr/local/bin/node]
 6: 0xd74536 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x16438d9  [/usr/local/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@2a3f2d026a71:/workspace/my-app# 
```

## System information

- OS: Windows
- Browser: Chrome

## Additional context

I'm using VSCode Devcontainer with Docker Compose

devcontainer.json
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/docker-existing-dockerfile
{
	"name": "Keystone Template",
	"context": "..",
	"workspaceFolder": "/workspace",
	"service": "app",
	"dockerComposeFile": "../docker-compose.yml",
	// Set *default* container specific settings.json values on container create.
	"settings": {
		"terminal.integrated.profiles.linux": "/bin/bash"
	},
	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"GitHub.copilot",
	],
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		3000,
		5432
	],
	// Uncomment the next line to run commands after the container is created - for example installing curl.
	// "postCreateCommand": "apt-get update && apt-get install -y curl",
	// Uncomment when using a ptrace-based debugger like C++, Go, and Rust
	// "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],
	// Uncomment to use the Docker CLI from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker.
	// "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],
	// Uncomment to connect as a non-root user if you've added one. See https://aka.ms/vscode-remote/containers/non-root.
	// "remoteUser": "inkuser"
}
```
