### ISSUE TITLE
PostgreSQL tables are not created in production

### ISSUE THREAD

**Issue by JMLX42** [keystonejs/keystone#7430]
## How to reproduce

1. Create a production build:

```
yarn install
yarn run build
```

2. Package the build in a container image using a `Dockerfile`:

```dockerfile
FROM registry.aerys.in/aerys/infrastructure/vendor/node-docker:16.14.0-0

COPY app/.keystone /app/.keystone
COPY app/package.json /app/package.json
COPY app/node_modules /app/node_modules

WORKDIR /app
```

3. Run the corresponding container in docker-compose:

```yml
version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.0.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - nginx-proxy-conf:/etc/nginx/conf.d
      - nginx-proxy-html:/usr/share/nginx/html
    networks:
      - reverse-proxy
  app:
    restart: unless-stopped
    networks:
      - database
      - reverse-proxy
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: "3000"
      VIRTUAL_PATH: "${KEYSTONE_VIRTUAL_PATH}"
      VIRTUAL_DEST: "/"
      KEYSTONE_SESSION_SECRET: "${KEYSTONE_SESSION_SECRET}"
      KEYSTONE_SESSION_SECURE: "${KEYSTONE_SESSION_SECURE}"
      KEYSTONE_DB_URL: "${KEYSTONE_DB_URL}"
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    networks:
      - database
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      PGDATA: "/data/postgres"
      POSTGRES_DB: "${DATABASE_NAME}"
  pgadmin:
    image: dpage/pgadmin4:6.7
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PATH: "${PGADMIN_VIRTUAL_PATH}"
      VIRTUAL_PORT: "80"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      SCRIPT_NAME: "${PGADMIN_SCRIPT_NAME}"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - database
      - reverse-proxy

networks:
  database:
  reverse-proxy:

volumes:
  postgres:
  pgadmin:
  nginx-proxy-conf:
  nginx-proxy-html:
```

## Expected result

The (missing) PostgreSQL tables are created when running `yarn run start` and the app is usable.

## Actual result

```
yarn run v1.22.17
$ keystone start
✨ Starting Keystone
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Preparing Admin UI Next.js app
✅ Admin UI ready
⭐️ Server Ready on http://localhost:3000
An error occurred handling a request for the Admin UI: Error: Prisma error: The table `public.User` does not exist in the current database.
    at Object.prismaError (/app/node_modules/@keystone-6/core/dist/graphql-errors-36f8a6f9.cjs.prod.js:34:10)
    at runWithPrisma (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:30:25)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:911:17)
    at async Promise.all (index 0)
    at async Object.runGraphQL [as run] (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2819:20)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2498:24)
    at async pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:894:21)
    at async Object.pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:1105:43)
    at async /app/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-872b84e1.cjs.prod.js:190:30 {
  locations: [ { line: 1, column: 35 } ],
  path: [ 'count' ],
  extensions: {
    prisma: { code: 'P2021', clientVersion: '3.11.0', meta: [Object] },
    code: 'KS_PRISMA_ERROR'
  }
}
An error occurred handling a request for the Admin UI: Error: Prisma error: The table `public.User` does not exist in the current database.
    at Object.prismaError (/app/node_modules/@keystone-6/core/dist/graphql-errors-36f8a6f9.cjs.prod.js:34:10)
    at runWithPrisma (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:30:25)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:911:17)
    at async Promise.all (index 0)
    at async Object.runGraphQL [as run] (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2819:20)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2498:24)
    at async pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:894:21)
    at async Object.pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:1105:43)
    at async /app/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-872b84e1.cjs.prod.js:190:30 {
  locations: [ { line: 1, column: 35 } ],
  path: [ 'count' ],
  extensions: {
    prisma: { code: 'P2021', clientVersion: '3.11.0', meta: [Object] },
    code: 'KS_PRISMA_ERROR'
  }
}
An error occurred handling a request for the Admin UI: Error: Prisma error: The table `public.User` does not exist in the current database.
    at Object.prismaError (/app/node_modules/@keystone-6/core/dist/graphql-errors-36f8a6f9.cjs.prod.js:34:10)
    at runWithPrisma (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:30:25)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:911:17)
    at async Promise.all (index 0)
    at async Object.runGraphQL [as run] (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2819:20)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2498:24)
    at async pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:894:21)
    at async Object.pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:1105:43)
    at async /app/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-872b84e1.cjs.prod.js:190:30 {
  locations: [ { line: 1, column: 35 } ],
  path: [ 'count' ],
  extensions: {
    prisma: { code: 'P2021', clientVersion: '3.11.0', meta: [Object] },
    code: 'KS_PRISMA_ERROR'
  }
}
An error occurred handling a request for the Admin UI: Error: Prisma error: The table `public.User` does not exist in the current database.
    at Object.prismaError (/app/node_modules/@keystone-6/core/dist/graphql-errors-36f8a6f9.cjs.prod.js:34:10)
    at runWithPrisma (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:30:25)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/types-for-lists-51d061d4.cjs.prod.js:911:17)
    at async Promise.all (index 0)
    at async Object.runGraphQL [as run] (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2819:20)
    at async Object.count (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:2498:24)
    at async pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:894:21)
    at async Object.pageMiddleware (/app/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.prod.js:1105:43)
    at async /app/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-872b84e1.cjs.prod.js:190:30 {
  locations: [ { line: 1, column: 35 } ],
  path: [ 'count' ],
  extensions: {
    prisma: { code: 'P2021', clientVersion: '3.11.0', meta: [Object] },
    code: 'KS_PRISMA_ERROR'
  }
}
```

**Comment by JMLX42** [comment]
Running `keystone postinstall` also fails:

```
root@9217c756dfd8:/app# yarn run postinstall
yarn run v1.22.17
$ keystone postinstall
Error: Cannot find module '/app/keystone'
Require stack:
- /app/node_modules/@keystone-6/core/dist/requireSource-07dc5fc7.cjs.prod.js
- /app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js
- /app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /app/node_modules/@keystone-6/core/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requireSource (/app/node_modules/@keystone-6/core/dist/requireSource-07dc5fc7.cjs.prod.js:93:18)
    at postinstall (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:607:54)
    at cli (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:668:12)
    at Object.<anonymous> (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:680:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@keystone-6/core/dist/requireSource-07dc5fc7.cjs.prod.js',
    '/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js',
    '/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js',
    '/app/node_modules/@keystone-6/core/bin/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JMLX42** [comment]
Might be related: https://github.com/keystonejs/keystone/discussions/7393

**Comment by JMLX42** [comment]
Running the following command made it possible to use Prisma to export the initial migration/SQL code:

```
docker compose \
    -f ./docker-compose.yml -f ./dev/docker-compose.yml \
    --env-file ./dev/.env \
    exec app yarn keystone prisma migrate dev
```

But now I do not know what to do to actually run that initial migration in production. Running `keystone prisma migrate deploy && keystone start` fails:

```
Error: Cannot find module '/app/keystone'
Require stack:
- /app/node_modules/@keystone-6/core/dist/requireSource-07dc5fc7.cjs.prod.js
- /app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js
- /app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /app/node_modules/@keystone-6/core/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requireSource (/app/node_modules/@keystone-6/core/dist/requireSource-07dc5fc7.cjs.prod.js:93:18)
    at prisma (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:559:54)
    at cli (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:666:12)
    at Object.<anonymous> (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:680:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@keystone-6/core/dist/requireSource-07dc5fc7.cjs.prod.js',
    '/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js',
    '/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js',
    '/app/node_modules/@keystone-6/core/bin/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But if I add the `keystone.ts` module, then I have to add the entire source code. Which is obviously not what I want here.

Is there anyway to run the Prisma migration code without the `keystone.ts` root module? `yarn run start` runs fine if the `start` script is just `keystone start`. Only `keystone prisma migrate deploy` fails because of that missing `keystone.ts` module.

**Comment by JMLX42** [comment]
I tryied running the `prisma` CLI directly, without success for now:

```
root@f04d7c58f2e7:/app# yarn prisma migrate deploy --schema ./node_modules/.prisma/client/schema.prisma 
yarn run v1.22.17
$ /app/node_modules/.bin/prisma migrate deploy --schema ./node_modules/.prisma/client/schema.prisma
Prisma schema loaded from node_modules/.prisma/client/schema.prisma
Error: Get config: Schema Parsing P1012

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:5
   | 
 4 | datasource postgresql {
 5 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JMLX42** [comment]
After:

- moving `node_modules/.prisma/client/schema.prisma` in the app's root directory
- setting a proper value for `DATABASE_URL`

The following command applied [the previously exported migration](https://github.com/keystonejs/keystone/issues/7430#issuecomment-1087458858):

```
root@f04d7c58f2e7:/app# yarn prisma migrate deploy                                                            
yarn run v1.22.17
$ /app/node_modules/.bin/prisma migrate deploy
Prisma schema loaded from schema.prisma
Datasource "postgresql": PostgreSQL database "keystone", schema "public" at "postgres:5432"

1 migration found in prisma/migrations

Applying migration `20220404112959_initial_db`

The following migration have been applied:

migrations/
  └─ 20220404112959_initial_db/
    └─ migration.sql
      
All migrations have been successfully applied.
Done in 1.28s.
```

**Comment by JMLX42** [comment]
> The following command applied https://github.com/keystonejs/keystone/issues/7430#issuecomment-1087458858:

Now the app runs find from the production build. I still have to figure out how can `DATABASE_URL` be set (I expect the `keystone` CLI to be the one doing it normally, but I cannot use the CLI because of [the error explained above](https://github.com/keystonejs/keystone/issues/7430#issuecomment-1087211483)).

In the meantime, I can workaround this problem by setting `DATABASE_URL` in `prod/docker-compose.yml`.

But it would still be nice to:

- Not have to set `DATABASE_URL`
- Be able to run `yarn keystone prisma migrate deploy` directly (instead of `yarn prisma migrate deploy`)

**Comment by JMLX42** [comment]
> In the meantime, I can workaround this problem by setting DATABASE_URL in prod/docker-compose.yml.

Actually that does not work:

- `prisma migrate deploy` *does* work
- but then `keystone start` does *not* work

```
Prisma schema loaded from schema.prisma
Datasource "postgresql": PostgreSQL database "keystone", schema "public" at "postgres:5432"

1 migration found in prisma/migrations


No pending migrations to apply.
✨ Starting Keystone
PrismaClientConstructorValidationError: Invalid value undefined for datasource "postgresql" provided to PrismaClient constructor.
It should have this form: { url: "CONNECTION_STRING" }
Read more at https://pris.ly/d/client-constructor
    at Object.datasources (/app/node_modules/.prisma/client/runtime/index.js:39989:19)
    at validatePrismaClientOptions (/app/node_modules/.prisma/client/runtime/index.js:40079:20)
    at new PrismaClient (/app/node_modules/.prisma/client/runtime/index.js:40168:9)
    at getKeystone (/app/node_modules/@keystone-6/core/dist/initConfig-641adecb.cjs.prod.js:3094:28)
    at Object.start (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.prod.js:468:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JMLX42** [comment]
> but then keystone start does not work

That was actually caused by a missing rebuild after refactoring the env var used by Keystone's connection URL.

In the end, the following works:

```json
{
  "name": "smartshape-license-manager",
  "version": "0.2.0",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "prisma migrate deploy && keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.51.0",
    "@keystone-6/auth": "^2.0.0",
    "@keystone-6/core": "^1.1.0",
    "@keystone-6/fields-document": "^2.0.0",
    "typescript": "^4.5.4",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@types/node": "^16.11.24",
    "@types/uuid": "^8.3.4"
  },
  "engines": {
    "node": "^14.15 || ^16.13"
  }
}
```

```dockerfile
FROM node:16

COPY app/.keystone /app/.keystone
COPY app/package.json /app/package.json
COPY app/node_modules /app/node_modules
COPY app/migrations /app/migrations
COPY app/schema.prisma /app/schema.prisma

WORKDIR /app
```

```yml
version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.0.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - nginx-proxy-conf:/etc/nginx/conf.d
      - nginx-proxy-html:/usr/share/nginx/html
    networks:
      - reverse-proxy
  app:
    image: app:latest
    restart: unless-stopped
    command: yarn run start
    networks:
      - database
      - reverse-proxy
    environment:
      NODE_ENV: "production"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: "3000"
      VIRTUAL_PATH: "${KEYSTONE_VIRTUAL_PATH}"
      VIRTUAL_DEST: "/"
      KEYSTONE_SESSION_SECRET: "${KEYSTONE_SESSION_SECRET}"
      KEYSTONE_SESSION_SECURE: "${KEYSTONE_SESSION_SECURE}"
      KEYSTONE_DATABASE_URL: "${KEYSTONE_DATABASE_URL}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_FORCE_PATH_STYLE: "${S3_FORCE_PATH_STYLE}"
      DATABASE_URL: "${KEYSTONE_DATABASE_URL}"
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    networks:
      - database
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      PGDATA: "/data/postgres"
      POSTGRES_DB: "${DATABASE_NAME}"

networks:
  database:
  reverse-proxy:

volumes:
  postgres:
  nginx-proxy-conf:
  nginx-proxy-html:
```

It would still be nice if someone from the KeystoneJS team could explain how the `start` script could be set to `keystone prisma migrate deploy && keystone start` instead of `prisma migrate deploy && keystone start`.
