### ISSUE TITLE
Cannot build Docker image from fresh Keystone 6 repo

### ISSUE THREAD

**Issue by yoerriwalstra** [keystonejs/keystone#7641]
## Reproduction
Either: clone [this repo](https://github.com/yoerriwalstra/keystone-docker), README contains instructions and expected output.
Or: 
1. install Keystone 6: `yarn create keystone-app`
2. <details>
  <summary>add `Dockerfile`</summary>
  ```
  FROM node:16-alpine
  WORKDIR /app
  COPY package.json yarn.lock ./
  RUN yarn
  COPY . .
  EXPOSE 3000
  CMD ["yarn", "dev"]
  ```
</details>
3. <details>
  <summary>add `docker-compose.yml`</summary>
  ```
  version: '3.8'

  services:
    app:
      build: .
      ports:
        - 4000:3000
      volumes:
        - ./:/app
      environment:
        - DB_CONNECTION=postgres
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_USER=root
        - DB_PASSWORD=secret
        - DB_NAME=database-name

    postgres:
      image: postgres:12
      ports:
        - 54320:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DATABASE=database-name

  volumes:
    postgres-data:
  ```
</details>
```
4. run `docker-compose up [-d]`

<!-- Please describe what you expected to happen -->
## Expect
Docker to build image and start running the application in development mode

<!-- Please add any screenshots if possible -->
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/48599583/174298396-85d5272e-8def-450e-8345-44fb0ac51dba.png">
